/*
 * ModelDB API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/medienlampe/modb-api/0.0.1/",
		Index,
	},

	Route{
		"AddContract",
		strings.ToUpper("Post"),
		"/medienlampe/modb-api/0.0.1/contract",
		AddContract,
	},

	Route{
		"DeleteContract",
		strings.ToUpper("Delete"),
		"/medienlampe/modb-api/0.0.1/contract/{contractId}",
		DeleteContract,
	},

	Route{
		"GetContractById",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/contract/{contractId}",
		GetContractById,
	},

	Route{
		"UpdateContract",
		strings.ToUpper("Put"),
		"/medienlampe/modb-api/0.0.1/contract/{contractId}",
		UpdateContract,
	},

	Route{
		"UploadFile",
		strings.ToUpper("Post"),
		"/medienlampe/modb-api/0.0.1/contract/{contractId}/addContractFile",
		UploadFile,
	},

	Route{
		"AddIdea",
		strings.ToUpper("Post"),
		"/medienlampe/modb-api/0.0.1/idea",
		AddIdea,
	},

	Route{
		"DeleteIdea",
		strings.ToUpper("Delete"),
		"/medienlampe/modb-api/0.0.1/idea/{ideaId}",
		DeleteIdea,
	},

	Route{
		"GetIdeaById",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/idea/{ideaId}",
		GetIdeaById,
	},

	Route{
		"UpdateIdea",
		strings.ToUpper("Put"),
		"/medienlampe/modb-api/0.0.1/idea/{ideaId}",
		UpdateIdea,
	},

	Route{
		"AddModel",
		strings.ToUpper("Post"),
		"/medienlampe/modb-api/0.0.1/model",
		AddModel,
	},

	Route{
		"DeleteModel",
		strings.ToUpper("Delete"),
		"/medienlampe/modb-api/0.0.1/model/{modelId}",
		DeleteModel,
	},

	Route{
		"FindModelsByTags",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/model/findByTags",
		FindModelsByTags,
	},

	Route{
		"GetModelById",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/model/{modelId}",
		GetModelById,
	},

	Route{
		"UpdateModel",
		strings.ToUpper("Put"),
		"/medienlampe/modb-api/0.0.1/model/{modelId}",
		UpdateModel,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/medienlampe/modb-api/0.0.1/user",
		CreateUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/medienlampe/modb-api/0.0.1/user/{username}",
		DeleteUser,
	},

	Route{
		"GetUserByName",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/user/{username}",
		GetUserByName,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/user/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Get"),
		"/medienlampe/modb-api/0.0.1/user/logout",
		LogoutUser,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/medienlampe/modb-api/0.0.1/user/{username}",
		UpdateUser,
	},
}
